name: db
description: Event Database package
version: 1.0.0

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  collection: ^1.16.0
  drift: ^1.6.0
#  path_provider: ^2.0.0
  logging: ^1.0.2
  path: ^1.8.1
#  drift_postgres:
#    git:
#      url: https://github.com/simolus3/drift.git
#      path: extras/drift_postgres

dev_dependencies:
  drift_dev: ^1.6.0
  build_runner: ^2.1.10
  lints: ^2.0.0
  test: ^1.16.0
