// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDTffHiNZ23Y_xIqqMU5p4l6yWgSECzyQ',
    appId: '1:247079421360:web:0c3e6061fb77a4310a0275',
    messagingSenderId: '247079421360',
    projectId: 'dgrpc-87463',
    authDomain: 'dgrpc-87463.firebaseapp.com',
    storageBucket: 'dgrpc-87463.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMjqIEQ3FZ0sYWc7_j5LHhGPukTpAtPxk',
    appId: '1:247079421360:android:2079a2691b68590c0a0275',
    messagingSenderId: '247079421360',
    projectId: 'dgrpc-87463',
    storageBucket: 'dgrpc-87463.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALaMcU3iZmatP-Gc6fWmqR5Xw1k3teraM',
    appId: '1:247079421360:ios:c31761522739da410a0275',
    messagingSenderId: '247079421360',
    projectId: 'dgrpc-87463',
    storageBucket: 'dgrpc-87463.appspot.com',
    iosClientId: '247079421360-mg5316lseq3cg8ntqg3hlv1borkfkqhj.apps.googleusercontent.com',
    iosBundleId: 'com.strangebrew',
  );
}
